# Generated by Django 5.2.8 on 2025-11-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order_number', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
