# Generated by Django 5.2.8 on 2025-11-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls the display order on the homepage.'),
        ),
    ]
