# Generated by Django 5.2.8 on 2025-11-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_contacdigitalmarketing'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContacDigitalMarketing',
            new_name='ContactDigitalMarketing',
        ),
    ]
