# Generated by Django 5.2.8 on 2025-12-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_service_subservice_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='solution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
