# Generated by Django 5.2.8 on 2025-12-08 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_leads_company_name_leads_phone_number_leads_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='service',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='SubService',
        ),
    ]
