# Generated by Django 5.2.8 on 2025-12-09 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_subservice_service_delete_feature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_description', models.TextField()),
                ('service_image', models.ImageField(upload_to='service_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.CreateModel(
            name='Subservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subservice_name', models.CharField(max_length=255)),
                ('subservice_description', models.TextField(blank=True, null=True)),
                ('sub_service_image', models.ImageField(upload_to='sub_service_images/')),
                ('service_heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subservices', to='dashboard.servicename')),
            ],
        ),
    ]
