# Generated by Django 5.2.8 on 2025-12-09 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_servicedigitalmarketing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_description_title', models.CharField(blank=True, max_length=255, null=True)),
                ('banner_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Solutions/')),
            ],
        ),
        migrations.CreateModel(
            name='solutionsDigitalMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='solution_digital_marketing/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolutionsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solutions_name', models.CharField(max_length=255)),
                ('solutions_description', models.TextField()),
                ('solutions_image', models.ImageField(upload_to='SolutionsName/')),
            ],
        ),
        migrations.CreateModel(
            name='Subsolutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solutions_name', models.CharField(max_length=255)),
                ('solutions_description', models.TextField(blank=True, null=True)),
                ('solutions_image', models.ImageField(upload_to='Subsolutions/')),
                ('solutions_heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='dashboard.solutionsname')),
            ],
        ),
    ]
