# Generated by Django 5.2.8 on 2026-01-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_homevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_features/')),
                ('main_feature', models.TextField(blank=True, null=True)),
                ('text1', models.CharField(blank=True, max_length=200, null=True)),
                ('text1_description', models.TextField(blank=True, null=True)),
                ('text2', models.CharField(blank=True, max_length=200, null=True)),
                ('text2_description', models.TextField(blank=True, null=True)),
                ('text3', models.CharField(blank=True, max_length=200, null=True)),
                ('text3_description', models.TextField(blank=True, null=True)),
                ('text4', models.CharField(blank=True, max_length=200, null=True)),
                ('text4_description', models.TextField(blank=True, null=True)),
                ('text5', models.CharField(blank=True, max_length=200, null=True)),
                ('text5_description', models.TextField(blank=True, null=True)),
                ('text6', models.CharField(blank=True, max_length=200, null=True)),
                ('text6_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
