# Generated by Django 5.2.8 on 2026-01-06 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_expertise_industry_ourworks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourworks',
            name='industries',
        ),
        migrations.AddField(
            model_name='ourworks',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='dashboard.industry'),
        ),
        migrations.RemoveField(
            model_name='ourworks',
            name='expertise',
        ),
        migrations.AddField(
            model_name='ourworks',
            name='expertise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='dashboard.expertise'),
        ),
    ]
