# Generated by Django 5.2.8 on 2026-01-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_ourworksdigitalmarketing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebanner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
