# Generated by Django 5.2.8 on 2026-01-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_conncepts_is_active_alter_footer_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusbanner1',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aboutusmission',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aboutustext1',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aboutustext2',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
