# Generated by Django 5.2.8 on 2026-01-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_aboutusbanner1_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insights',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
