# Generated by Django 5.2.8 on 2026-01-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_insights_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='our_insights/')),
                ('insight_date', models.CharField(help_text='e.g., 6 months, 1 week, 1 year', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Our Insight',
                'verbose_name_plural': 'Our Insights',
                'ordering': ['-created_at'],
            },
        ),
    ]
