# Generated by Django 5.2.8 on 2026-01-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_ourinsights'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourworks',
            name='banner2_image',
            field=models.ImageField(blank=True, null=True, upload_to='our_works/banners/'),
        ),
        migrations.AddField(
            model_name='ourworks',
            name='banner2_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourworks',
            name='banner_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourworks',
            name='banner_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourworks',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='our_works/banners/'),
        ),
        migrations.AddField(
            model_name='ourworks',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourworks',
            name='launch_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ourworks',
            name='system',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ourworks',
            name='time_scale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
