# Generated by Django 5.2.8 on 2026-01-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_ourworks_banner2_image_ourworks_banner2_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourinsights',
            name='category',
            field=models.CharField(blank=True, help_text='e.g., Technology, Business, Marketing', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ourinsights',
            name='services',
            field=models.TextField(blank=True, help_text='Comma separated values. Example: Web Development, SEO, UI/UX Design', null=True),
        ),
    ]
