# Generated by Django 5.2.8 on 2026-01-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_insightchallengesection_insightchallengeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='subservice',
            name='subservice_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
