# Generated by Django 5.2.8 on 2026-01-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_subservice_subservice_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsolutions',
            name='solutions_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
