# Generated by Django 5.2.8 on 2026-01-25 15:26

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_rename_status_home_is_active_leads_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurWorkSection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('corporate_clients', models.CharField(default='100+', help_text='e.g., 100+', max_length=50)),
                ('custom_designs', models.CharField(default='500+', help_text='e.g., 500+', max_length=50)),
                ('years_experience', models.CharField(default='10+', help_text='e.g., 10+', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ourwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section2_stats', to='dashboard.ourworks')),
            ],
            options={
                'verbose_name': 'Our Work Section 2',
                'verbose_name_plural': 'Our Work Section 2',
            },
        ),
    ]
