# Generated by Django 5.2.8 on 2026-01-25 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_ourworksection2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGoalsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(default='PROJECT GOALS', max_length=200)),
                ('main_title', models.CharField(default='Objectives', max_length=200)),
                ('main_description', models.TextField(help_text='e.g., To visually highlight customization quality and brand reliability.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ourwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_goals_section', to='dashboard.ourworks')),
            ],
            options={
                'verbose_name': 'Project Goals Section',
                'verbose_name_plural': 'Project Goals Sections',
            },
        ),
        migrations.CreateModel(
            name='ProjectGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='e.g., Product Showcase, Brand Value, Market Reach', max_length=200)),
                ('description', models.TextField(help_text='e.g., Highlight diary quality and finish.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which goals appear')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='dashboard.projectgoalssection')),
            ],
            options={
                'verbose_name': 'Project Goal',
                'verbose_name_plural': 'Project Goals',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
