# Generated by Django 5.2.8 on 2026-01-25 16:00

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_projectgoalssection_projectgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', cloudinary.models.CloudinaryField(blank=True, help_text='Large banner image showcasing multiple designs', max_length=255, null=True, verbose_name='image')),
                ('main_heading', models.CharField(default='WHAT WE SOLVED', max_length=200)),
                ('main_title', models.CharField(default='Challenges', max_length=200)),
                ('main_description', models.TextField(help_text='e.g., Balancing informative content with engaging design.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ourwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenges_section', to='dashboard.ourworks')),
            ],
            options={
                'verbose_name': 'Challenges Section',
                'verbose_name_plural': 'Challenges Sections',
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Optional challenge illustration image', max_length=255, null=True, verbose_name='image')),
                ('heading', models.CharField(help_text='e.g., Information Density, Student Engagement', max_length=200)),
                ('description', models.TextField(help_text='e.g., Presenting large amounts of data clearly.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which challenges appear')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='dashboard.challengessection')),
            ],
            options={
                'verbose_name': 'Challenge',
                'verbose_name_plural': 'Challenges',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
