# Generated by Django 5.2.8 on 2026-01-25 16:16

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_challengessection_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='image',
        ),
        migrations.CreateModel(
            name='CreativeDirectionSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(help_text='e.g., Wellness-Focused Visual Identity', max_length=200)),
                ('main_description', models.TextField(help_text='e.g., A clean, elegant design language that reflects peace and wellness.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ourwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creative_direction_section', to='dashboard.ourworks')),
            ],
            options={
                'verbose_name': 'Creative Direction Section',
                'verbose_name_plural': 'Creative Direction Sections',
            },
        ),
        migrations.CreateModel(
            name='CreativeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(help_text='Creative item image', max_length=255, verbose_name='image')),
                ('title', models.CharField(help_text='e.g., SOCIAL MEDIA DESIGN, PROMOTIONAL CREATIVES', max_length=200)),
                ('description', models.TextField(help_text='e.g., Minimal and calming social creatives.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which items appear')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_items', to='dashboard.creativedirectionsection')),
            ],
            options={
                'verbose_name': 'Creative Item',
                'verbose_name_plural': 'Creative Items',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
