# Generated by Django 5.2.8 on 2026-01-25 16:36

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_remove_challenge_image_creativedirectionsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='INTERACTIVE EXPERIENCE', help_text='Small label above title', max_length=100)),
                ('title', models.CharField(help_text='e.g., 3D Visualization & Virtual Tours', max_length=200)),
                ('description', models.TextField(help_text='Long description about the mobile experience')),
                ('mobile_image_1', cloudinary.models.CloudinaryField(help_text='First mobile image/screenshot', max_length=255, verbose_name='image')),
                ('mobile_image_2', cloudinary.models.CloudinaryField(help_text='Second mobile image/screenshot', max_length=255, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ourwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_section', to='dashboard.ourworks')),
            ],
            options={
                'verbose_name': 'Mobile Section',
                'verbose_name_plural': 'Mobile Sections',
            },
        ),
    ]
