# Generated by Django 5.2.8 on 2026-01-25 17:00

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_mobilesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='Section heading', max_length=200)),
                ('description', models.TextField(help_text='Section description')),
                ('image_1', cloudinary.models.CloudinaryField(help_text='First image', max_length=255, verbose_name='image')),
                ('image_2', cloudinary.models.CloudinaryField(help_text='Second image', max_length=255, verbose_name='image')),
                ('image_3', cloudinary.models.CloudinaryField(help_text='Third image', max_length=255, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ourwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section4', to='dashboard.ourworks')),
            ],
            options={
                'verbose_name': 'Section 4',
                'verbose_name_plural': 'Section 4',
            },
        ),
        migrations.CreateModel(
            name='Section5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='Section heading', max_length=200)),
                ('description', models.TextField(help_text='Section description')),
                ('image', cloudinary.models.CloudinaryField(help_text='Main section image', max_length=255, verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ourwork', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section5', to='dashboard.ourworks')),
            ],
            options={
                'verbose_name': 'Section 5',
                'verbose_name_plural': 'Section 5',
            },
        ),
    ]
