# Generated by Django 5.2.8 on 2026-01-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_section4_section5'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourworksection2',
            options={'ordering': ['-created_at'], 'verbose_name': 'Our Work Section 2', 'verbose_name_plural': 'Our Work Section 2'},
        ),
        migrations.RemoveField(
            model_name='ourworksection2',
            name='corporate_clients',
        ),
        migrations.RemoveField(
            model_name='ourworksection2',
            name='custom_designs',
        ),
        migrations.RemoveField(
            model_name='ourworksection2',
            name='years_experience',
        ),
        migrations.AddField(
            model_name='ourworksection2',
            name='stat1_count',
            field=models.CharField(default='1000+', help_text='e.g., 1000+, 95%, 15+', max_length=50),
        ),
        migrations.AddField(
            model_name='ourworksection2',
            name='stat1_text',
            field=models.CharField(default='Students Guided', help_text='Label for statistic 1', max_length=100),
        ),
        migrations.AddField(
            model_name='ourworksection2',
            name='stat2_count',
            field=models.CharField(default='15+', help_text='e.g., 1000+, 95%, 15+', max_length=50),
        ),
        migrations.AddField(
            model_name='ourworksection2',
            name='stat2_text',
            field=models.CharField(default='Partner Universities', help_text='Label for statistic 2', max_length=100),
        ),
        migrations.AddField(
            model_name='ourworksection2',
            name='stat3_count',
            field=models.CharField(default='95%', help_text='e.g., 1000+, 95%, 15+', max_length=50),
        ),
        migrations.AddField(
            model_name='ourworksection2',
            name='stat3_text',
            field=models.CharField(default='Application Success Rate', help_text='Label for statistic 3', max_length=100),
        ),
        migrations.AlterField(
            model_name='ourworksection2',
            name='description',
            field=models.TextField(default='Section description goes here.', help_text='e.g., Strong visuals and messaging helped position the brand...'),
        ),
        migrations.AlterField(
            model_name='ourworksection2',
            name='title',
            field=models.CharField(default='Section Title', help_text='e.g., Building Trust Through Clear Communication', max_length=200),
        ),
    ]
