# Generated by Django 5.2.8 on 2026-01-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_alter_ourworksection2_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativedirectionsection',
            name='main_heading',
            field=models.CharField(default='Creative Direction', help_text='e.g., Creative Direction', max_length=200),
        ),
    ]
