# Generated by Django 5.2.8 on 2026-02-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_subservice_meta_description_subservice_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subservice',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
