# Generated by Django 5.2.8 on 2026-02-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_alter_subservice_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsolutions',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subsolutions',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='subsolutions',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subsolutions',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
