# Generated by Django 5.2.8 on 2026-02-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_subsolutions_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourworksection2',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourworksection2',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ourworksection2',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourworksection2',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ourworksection2',
            name='stat1_count',
            field=models.CharField(default='1000+', max_length=50),
        ),
        migrations.AlterField(
            model_name='ourworksection2',
            name='stat1_text',
            field=models.CharField(default='Students Guided', max_length=100),
        ),
        migrations.AlterField(
            model_name='ourworksection2',
            name='stat2_count',
            field=models.CharField(default='15+', max_length=50),
        ),
        migrations.AlterField(
            model_name='ourworksection2',
            name='stat2_text',
            field=models.CharField(default='Partner Universities', max_length=100),
        ),
        migrations.AlterField(
            model_name='ourworksection2',
            name='stat3_count',
            field=models.CharField(default='95%', max_length=50),
        ),
        migrations.AlterField(
            model_name='ourworksection2',
            name='stat3_text',
            field=models.CharField(default='Application Success Rate', max_length=100),
        ),
    ]
