# Generated by Django 5.2.8 on 2026-02-12 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_insights_meta_description_insights_meta_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSection1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_section1', to='dashboard.servicename')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_section2', to='dashboard.servicename')),
            ],
        ),
    ]
