# Generated by Django 5.2.8 on 2026-02-12 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_servicesection1_servicesection2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesection1',
            options={'verbose_name': 'Service Section 1', 'verbose_name_plural': 'Service Section 1'},
        ),
        migrations.AlterModelOptions(
            name='servicesection2',
            options={'ordering': ['-created_at'], 'verbose_name': 'Service Section 2', 'verbose_name_plural': 'Service Section 2'},
        ),
        migrations.RemoveField(
            model_name='servicesection1',
            name='service_heading',
        ),
        migrations.RemoveField(
            model_name='servicesection2',
            name='service_heading',
        ),
        migrations.AddField(
            model_name='servicesection1',
            name='subservice',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='section1', to='dashboard.subservice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesection2',
            name='subservice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='section2_items', to='dashboard.subservice'),
            preserve_default=False,
        ),
    ]
