# Generated by Django 5.2.8 on 2026-02-12 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_alter_servicesection1_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesection1',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicesection2',
            options={},
        ),
        migrations.RemoveField(
            model_name='servicesection1',
            name='subservice',
        ),
        migrations.RemoveField(
            model_name='servicesection2',
            name='subservice',
        ),
        migrations.AddField(
            model_name='servicesection1',
            name='service_heading',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_section1', to='dashboard.servicename'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesection2',
            name='service_heading',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_section2', to='dashboard.servicename'),
            preserve_default=False,
        ),
    ]
