# Generated by Django 5.2.8 on 2026-02-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_alter_servicesection1_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insights',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='insights',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='insights',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='insights',
            name='slug',
        ),
        migrations.AddField(
            model_name='ourinsights',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourinsights',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ourinsights',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourinsights',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
