# Generated by Django 5.2.8 on 2026-02-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_remove_insights_meta_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourworksection2',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='ourworksection2',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='ourworksection2',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='ourworksection2',
            name='slug',
        ),
        migrations.AddField(
            model_name='ourworks',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ourworks',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ourworks',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ourworks',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
