# Generated by Django 5.2.8 on 2026-02-13 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_remove_ourworksection2_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionsSection1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solutions_heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section1_items', to='dashboard.solutionsname')),
            ],
            options={
                'verbose_name': 'Solution Section 1',
                'verbose_name_plural': 'Solution Section 1',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SolutionsSection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solutions_heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section2_items', to='dashboard.solutionsname')),
            ],
            options={
                'verbose_name': 'Solution Section 2',
                'verbose_name_plural': 'Solution Section 2',
                'ordering': ['-created_at'],
            },
        ),
    ]
