# Generated by Django 5.2.8 on 2026-02-13 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_solutionssection1_solutionssection2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesection1',
            name='service_heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_section1', to='dashboard.subservice'),
        ),
        migrations.AlterField(
            model_name='servicesection2',
            name='service_heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_section2', to='dashboard.subservice'),
        ),
    ]
