# Generated by Django 5.2.8 on 2026-02-15 20:28

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_alter_servicesection1_service_heading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='design/banner/')),
                ('banner_heading', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='solutionssection1',
            name='solutions_heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section1_items', to='dashboard.subsolutions'),
        ),
        migrations.AlterField(
            model_name='solutionssection2',
            name='solutions_heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section2_items', to='dashboard.subsolutions'),
        ),
        migrations.CreateModel(
            name='DesignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='design_image')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.design')),
            ],
        ),
    ]
