# Generated by Django 5.2.8 on 2026-02-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_alter_location_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourworks',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
