# Generated by Django 5.2.8 on 2026-03-08 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_alter_ourworks_slug'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='ourworks',
        #     name='slug',
        #     field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        # ),
        migrations.CreateModel(
            name='InsightAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='achievement', to='dashboard.ourinsights')),
            ],
        ),
        migrations.CreateModel(
            name='InsightAchievementPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='dashboard.insightachievement')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InsightGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='growth', to='dashboard.ourinsights')),
            ],
        ),
        migrations.CreateModel(
            name='InsightResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='dashboard.ourinsights')),
            ],
        ),
        migrations.CreateModel(
            name='InsightResultBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='insight_results/')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='dashboard.insightresult')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InsightStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insight', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strategy', to='dashboard.ourinsights')),
            ],
        ),
        migrations.CreateModel(
            name='InsightStrategyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='dashboard.insightstrategy')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InsightStrategyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='dashboard.insightstrategyblock')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
